# Generated by Django 2.0.6 on 2019-02-28 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('validationcwApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='newCarForm',
            new_name='newCarModel',
        ),
    ]
